import 'package:flutter/material.dart';
import 'dart:convert';

class EventSuggestionScreen extends StatefulWidget {
  const EventSuggestionScreen({super.key, required this.suggestionJson});
  
  // 接收从 AI 传回来的 JSON 字符串
  final String suggestionJson;

  @override
  State<EventSuggestionScreen> createState() => _EventSuggestionScreenState();
}

class _EventSuggestionScreenState extends State<EventSuggestionScreen> {
  
  // 辅助方法：构建列表布局
  Widget buildList(List items) {
    if (items.isEmpty) return const Text("None");
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: items
          .map(
            (item) => Padding(
              padding: const EdgeInsets.symmetric(vertical: 4.0),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text("• ", style: TextStyle(fontWeight: FontWeight.bold)),
                  Expanded(child: Text(item.toString())),
                ],
              ),
            ),
          )
          .toList(),
    );
  }

  @override
  Widget build(BuildContext context) {
    Map<String, dynamic> decoded;
    try {
      decoded = jsonDecode(widget.suggestionJson);
    } catch (e) {
      return const Scaffold(body: Center(child: Text("Error parsing data")));
    }


    final String eventTitle = decoded['event_title'] ?? 'Event Proposal';
    final String description = decoded['description'] ?? 'No description provided.';
    final List schedule = decoded['schedule'] ?? [];
    final List tasks = decoded['tasks'] ?? [];
    final List itemsNeeded = decoded['items_needed'] ?? [];

    return Scaffold(
      appBar: AppBar(
        title: const Text("AI Event Suggestion"),
        backgroundColor: Colors.indigo,
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                eventTitle,
                style: const TextStyle(
                  fontSize: 26,
                  fontWeight: FontWeight.bold,
                  color: Colors.indigoAccent,
                ),
              ),
              const SizedBox(height: 10),
              
              const Text('Overview:', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              Text(description, style: const TextStyle(fontSize: 16)),
              const Divider(height: 30),

              const Text('Proposed Schedule:',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.blueGrey)),
              const SizedBox(height: 8),
              buildList(schedule),
              const SizedBox(height: 20),

              const Text('Key Tasks & Roles:',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.blueGrey)),
              const SizedBox(height: 8),
              buildList(tasks),
              const SizedBox(height: 20),

              const Text('Preparation Checklist:',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.blueGrey)),
              const SizedBox(height: 8),
              buildList(itemsNeeded),
              
              const SizedBox(height: 30),
              const Center(
                child: Text("Generated by AI Event Planner", 
                  style: TextStyle(color: Colors.grey, fontStyle: FontStyle.italic)),
              ),
            ],
          ),
        ),
      ),
    );
  }
}