// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy01IuUZqrxCR92FWDEgQXI_uoM5_sasc',
    appId: '1:22535116947:web:ec27b5b11b5e7cce555566',
    messagingSenderId: '22535116947',
    projectId: 'cdz-flutter',
    authDomain: 'cdz-flutter.firebaseapp.com',
    storageBucket: 'cdz-flutter.firebasestorage.app',
    measurementId: 'G-YR2EF8L8TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdeYSBtbgjrhg1pTc21JZCCittD9ajNYg',
    appId: '1:22535116947:android:b078921f15ec8575555566',
    messagingSenderId: '22535116947',
    projectId: 'cdz-flutter',
    storageBucket: 'cdz-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARKJ-HDfUgbqknnpFH9mLWeFQiNFuEVa0',
    appId: '1:22535116947:ios:8e745998ef033f66555566',
    messagingSenderId: '22535116947',
    projectId: 'cdz-flutter',
    storageBucket: 'cdz-flutter.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARKJ-HDfUgbqknnpFH9mLWeFQiNFuEVa0',
    appId: '1:22535116947:ios:8e745998ef033f66555566',
    messagingSenderId: '22535116947',
    projectId: 'cdz-flutter',
    storageBucket: 'cdz-flutter.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy01IuUZqrxCR92FWDEgQXI_uoM5_sasc',
    appId: '1:22535116947:web:d70867f89c63449c555566',
    messagingSenderId: '22535116947',
    projectId: 'cdz-flutter',
    authDomain: 'cdz-flutter.firebaseapp.com',
    storageBucket: 'cdz-flutter.firebasestorage.app',
    measurementId: 'G-L6W22MZV0P',
  );
}